name: "Release"
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build-extension:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            target: linux-x86_64
          - os: ubuntu-22.04-arm
            target: linux-aarch64
          - os: macos-13
            target: macos-x86_64
          - os: macos-14
            target: macos-aarch64
          - os: windows-2019
            target: windows-x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: make loadable-release
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: dist/release/*

  dist:
    runs-on: ubuntu-latest
    needs:
      [
        build-extension,
      ]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - uses: actions/download-artifact@v4
        with:
          path: dist/
      - run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/asg017/sqlite-dist/releases/download/v0.0.1-alpha.19/sqlite-dist-installer.sh | sh
      - run: sqlite-dist ./sqlite-dist.toml --input dist/ --output distx/ --version $(cat VERSION)
      - run: |
          gh release upload ${{ github.ref_name }} \
            distx/github_releases/* \
            distx/spm/* \
            distx/sqlpkg/* \
            distx/checksums.txt \
            distx/sqlite-dist-manifest.json \
            distx/install.sh
        env:
          GH_TOKEN: ${{ github.token }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: uv publish distx/pip/*
        env:
          UV_PUBLISH_USERNAME: __token__
          UV_PUBLISH_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}